### ISSUE TITLE
Question about wait-on-transfer.sh

### ISSUE THREAD

**Issue by jaswilli** [globus/automation-examples#5]
The Globus CLI has a command to poll for task completion: `globus task wait <task_id>`. Does `wait-on-transfer.sh` fill some gap that's missing in the CLI?

It seems strange that we'd highlight a way to duplicate functionality that exists in the CLI. Apologies if I'm missing something here.

**Comment by rpwagner** [comment]
Actually, I just didn’t know it was there. A user asked for an example blocker script so I put this one together. The only thing I’ll need to  I check about the CLI command is whether it has a timeout option. That was part of the request.

**Comment by jaswilli** [comment]
> I’ll need to I check about the CLI command is whether it has a timeout option

It does. `globus task wait <task_id> --timeout <seconds>`

**Comment by rpwagner** [comment]
Is there a way to distinguish between failing tasks and timeouts being exceeded, or could we add that via different exit codes?

**Comment by jaswilli** [comment]
Both return the same exit code (`1`) just like your script here but visually there's a message written to stderr noting the timeout period has expired.

The CLI could exit with a different non-zero code for timeouts if we think that would be a useful thing to do.

**Comment by rpwagner** [comment]
The use case is being able to distinguish between a failed transfer and a transfer that has exceeded a certain window but is still progressing. The user asked for the latter case to return `0`, but I agree that another non-zero code is preferable. Would you like me to include you on the email thread with the user or just reply here if that will work for the user? An alternative would be to allow the user to set the code for this specifically.

**Comment by jaswilli** [comment]
Allowing the user to map their own exit code to a timeout is certainly something we could do, so if someone wants to use `0` they would be able to do that.

**Comment by rpwagner** [comment]
If that was in place, then everything for the use case driving this script is covered, and no need to ask the user. Something like 
```
@click.option('--active-timeout-code', 'int', default=1,
              help='Code returned when the timeout window is exceeded but the transfer is still progressing (ACTIVE)')
```
?

The this script becomes
```
globus task wait -H --polling-interval 10 --active-timeout-code 0 <transfer ID>
```

And I have no preference for `--active-timeout-code` or any other flag.

**Comment by jaswilli** [comment]
Can be tracked here: https://github.com/globus/globus-cli/issues/450

**Comment by rpwagner** [comment]
Thanks for pointing this out and taking on the change.

**Comment by rpwagner** [comment]
@jaswilli can you let me know here when the update hits PyPI and I'll update this repo, tell the user, etc? Thanks

**Comment by jaswilli** [comment]
CLI v1.10 has been released. Changelog is here: https://github.com/globus/globus-cli/blob/master/changelog.adoc#1100

**Comment by rpwagner** [comment]
Excellent! Thanks again for pointing this out. It was all human error on my side.
